keys: # cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age
  - &chn age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
  - &pc age1ffvr5pqd2lfj24e3fh53s92z6h76fda3du4y4k6r3yjumdwvpfgqzj033a
  - &vps6 age164tyqklwhdm57tfm5u863mdt2xrzrrzac4py8a0j9y6kzqcjy9zsp073t6
  - &vps7 age137x7csalutwvfygvvzpemlsywvdxj3j4z93a50z2sjx03w6zau8q3r5902
  - &yoga age1qrea4twxdhd7fnvlq5v45528c90qy6hp2wa55kghsxzgut6n6fxs7w6u42
  - &nas age19lhcwk37jmvn6z0v4dpdfh0k4u23f76twdjknc0p7atktf37rd7s4t4wj3
creation_rules:
  - path_regex: secrets/pc/.*$
    key_groups:
    - age:
      - *chn
      - *pc
  - path_regex: secrets/vps6/.*$
    key_groups:
    - age:
      - *chn
      - *vps6
  - path_regex: secrets/vps7/.*$
    key_groups:
    - age:
      - *chn
      - *vps7
  - path_regex: secrets/nas/.*$
    key_groups:
    - age:
      - *chn
      - *nas
  - path_regex: secrets/xmupc1/.*$
    key_groups:
    - age:
      - *chn
  - path_regex: secrets/yoga/.*$
    key_groups:
    - age:
      - *chn
      - *yoga
