keys:
  - &chn age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
  - &chn-PC age1ffvr5pqd2lfj24e3fh53s92z6h76fda3du4y4k6r3yjumdwvpfgqzj033a
  - &vps6 age164tyqklwhdm57tfm5u863mdt2xrzrrzac4py8a0j9y6kzqcjy9zsp073t6
creation_rules:
  - path_regex: secrets/chn-PC\.yaml$
    key_groups:
    - age:
      - *chn
      - *chn-PC
  - path_regex: secrets/vps6\.yaml$
    key_groups:
    - age:
      - *chn
      - *vps6
