acme:
    cloudflare.ini: ENC[AES256_GCM,data:k7ojGrQQN81OGh391ISD0vfmQF7P3Iiuyx4ck7FxB9h3hFyl6HsiJxp3tIKsFBirbHzePEtXZOYmYUkqqw2i8dY=,iv:RX1BpzeznkrXhLVoI1YwrlRDnkQqGYNw/xwQvN8P9JM=,tag:TOfGt4QwxAY2j/c1deKFoA==,type:str]
nginx:
    maxmind-license: ENC[AES256_GCM,data:VmOiT6FYFEkMYTstz+4+4MSZSeOgHQh437j6Ccd/EhYVEa8iKI1PfA==,iv:C90KL+tv3ZpbnHqsKv0hLUprM1RKagCdU2ne3Z9Hor4=,tag:QVlJZL+bnVpjEzy4VF31vA==,type:str]
xray-client:
    uuid: ENC[AES256_GCM,data:+UJjAWH31CbeQjWoFNeBW5Sqt/RoBTbgouelDYGKfK5G6uY+,iv:AzIpLV7NYeqZUmZ6PZNYFbml9TUPRLTFPeiRQm8S7X0=,tag:/lDbaFCUHmVYDHtmrMisGA==,type:str]
wireguard:
    privateKey: ENC[AES256_GCM,data:49BPDoNzzTJFRpIXw3wMRStwd66aG848Z5EUMPwMMZdWeFPBdDB6cHm9zQM=,iv:R6zsmALbV3YMFlIQlGpLqL5mNXeQXn6MbhAFB7T+nLI=,tag:WOrebshoF1V0u2+GnBMTXw==,type:str]
users:
    xll: ENC[AES256_GCM,data:hFXYsNx3VL3LQ9WK6VZyyUQEFwGlU24uLc/87ZloqKXP+z0Mn530dsE8ujs0bu4kBYf9v/Z3/ureX3w1ww9wTzb+peRum+65fw==,iv:VcbvNj+TwgQYrK53mNriZyNCnPyzNoIMXROJW2dk27U=,tag:UT7o/7npyMPXuCuWxeji4w==,type:str]
    zem: ENC[AES256_GCM,data:g6+j8FNa25CMkGL1CK6L3B+U+u7AEG+ITuRC0SZ6n0VmRacB/A0z/7JjmWNZdtqbiFSAqYmlBHYazGa6mdGG4dGchJnlJJIdqA==,iv:3UnzM86OpJhX5i/wkFRfJywSN8zD/PG09Mcsw54cK8o=,tag:RZUZnQQID+QIo6pH7vWwSg==,type:str]
    yjq: ENC[AES256_GCM,data:8ubORdhLjmCYI4mAQglUAxVe6dkfhidU2d2IMAN1EDziF8s2ks0r3oSkHhnl1C9dMu2o5EmWSMR/IzyFwTqpPkQajhzrdCR+6A==,iv:SmmYdZo+8/PS3XxrFNz2U1hYABd72jE0DCNCflnLTJk=,tag:IfquGpG94mPqsQQ1sLNv1Q==,type:str]
    yxy: ENC[AES256_GCM,data:XQW01xjy3u0P8Ln9bsCLkE8NGrp312ye2ROgF8eQ7bkGq8p+NHE2WrtwnGESx9sQN1HLdYhntyiU/mU0eAKXK1Rr1QAwzLkbnw==,iv:uJC2bQ6EGMI7BhgujeN9ZRfc6uUkd8bgtUqljGHxrH8=,tag:RRdpDmZyNk5CVoiQXHjzng==,type:str]
    gb: ENC[AES256_GCM,data:8szWbJHwh/qGe0QZrHOpu9HHN2x5koavczdeDTvyT7rQA1iNHinJVgmLHU2s8dMHaUC/uvTxTDaRXFLdVbSaJyyxzgJmIQtKLg==,iv:ZqlacGz9J6oysE3qbOYu5UleUj0eG4lMYmYn1p7iBT4=,tag:j0Dag9tuuNHSR5qtlcWIfw==,type:str]
mariadb:
    slurm: ENC[AES256_GCM,data:3tf2WKmoRqQ1TvJjuVeOjGAxToRm1T3oRG+XKGKeC/GCIDitWiZJyYDDlLlSuVjjVuaiS2uMpA/yUr9sTbxl7Q==,iv:PMDmzcHb3wjE6vx1JqcWp0UDdnc6SMZ2mn16uxQ/qXw=,tag:KFSjqmStqn2DfHcWEbGOTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreXVOckI3MHZMdlE0ODhj
            SHM4TitaZS8zR1lsM050OFI3U2RtbmhzWXlJCnB1V1NXc0VzdlB6Z0d1bnJiSXdr
            SDBHMGtTb0l4cEthd2kvNjV4ajRtSkkKLS0tIDBHMVltT2JVV3d3VjA4YmhvL3g3
            UDRVZ3luNkRQNFdtYUF4bm4vd05mdkEKlX67g6DrurDVrSG2+5lj4wZ+8xfEpu9K
            jAZ8pt1pCsrbkGOWOBD5PqbWn0X1Dms6F4qiyefcQlmIjhXc9/PPLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-26T04:16:48Z"
    mac: ENC[AES256_GCM,data:w1nEHFIADqiRP0OIK34R4epeiqEmSrV6tzAPUnVpDOHZ3Ia2tuCNcgoAjGEUehPv77Hr7flHWHVpO1FnLtujZHyuEYZGzIzi7zqG2WmRGIkeGlwgWAJZXNr7xIRF7a7LpEY2o7hnPzxAbdm3MAiWFIW9ZaXlHft20y3IosL4vdM=,iv:bxVM4kmcrDYxjus67bH0gehzuh3Yj6xxqryihr5dbt8=,tag:dnG7qb9sRPvVHn/rz5lu+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
