hello: ENC[AES256_GCM,data:gYWUY12BwOdE0/xVvxPzfJRlpkghKUIPjSr8f6EImTGT2xzpPf+zsKCSAhCpFA==,iv:7Z/yCADBqjerLBq1bJapZ2K6hajSpakvb/lbkmUvpHw=,tag:rvI/70cZyy33XB+XQ6ERlg==,type:str]
example_key: ENC[AES256_GCM,data:dRe2yzZieLjgWjviSA==,iv:pTNmxYo6pewcavnFXt4i4a6ybxdc5kF4LAPbOY9RbD0=,tag:h7Dtrjvt954lIVryCnDfoQ==,type:str]
example_array:
    - ENC[AES256_GCM,data:0xfhD2tQuQsIrJMAD40=,iv:8E214l7PoJwjP9wkGMkN91s2vRefYzqqNuANappwGTo=,tag:TglXrM74sE6ukc1mQsPRIA==,type:str]
    - ENC[AES256_GCM,data:mj9YI0JTBd/MNE/czkk=,iv:BCUQEOnlyflyXJwuIz2hwUDISS4JjXFKAPknxdfrW5M=,tag:r+2zvCKxAjWt2TuMTaVtaw==,type:str]
example_number: ENC[AES256_GCM,data:0rxe8tlinN1pPg==,iv:sReZgb8dadC/LUcLTScRA5X8DblllMdRGdYGNtPDlkk=,tag:BKNzaRlXTaMlrwTE1gh/sw==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:li2/7Q==,iv:QrNSpMbnGbp94wmTUjI3HISMmtGwy+sLYSfdALUf5kA=,tag:mcUYXhcjqUhyN4zjuBqiXg==,type:bool]
    - ENC[AES256_GCM,data:7WLBDdM=,iv:NdAvGVpfPrd2IuRgW6yLGP6Hum5Oo4vVyaVykTfMB6U=,tag:N5bxC/2+347C4/gHsqRKWA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV25wc1hPNE9wdnIxc25p
            WjBxUHhVOCt0RFlhRlc1SVZnMlgyK1diS2lFCnUvdnVvaS9nTU9mNGMyQXQ2bHJ1
            c0NDWW5HZUpacDBnbnJhZkdVWkNWc0kKLS0tIHR2WHlKYXVybVZmMk9pWERkOGZB
            YTlUZGdNT0d5MGEzOWczSTVGeW9DVVUKeQnRRGJYFTnbF6gzxpIKpbvMWt61jliH
            phg2S8SRvSty+78mn/n/qs0rol/87E38ToJf7c+1E2PkDDAQ9d76YQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4stuz0vr7gs7pqwjrmezam44702jp2vmqaqyxw0l0r42kf9updq4dfhrw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcTZIczFWSHhPMGZ2Kzdu
            SnBxV1B4TFV1ckRRM1kvWkJHUG9QbzEwV2drCnRydkRnK1VjUHRHRkh2eFo1UEt1
            cUV1Ymt1SkRnS0JOMkdsWHA2ZXBQNEUKLS0tIFFYeVJoMGd5UmVsN0dKL01peFRM
            NE5vNm96MHpTNk5sYTdFTDRyZVFzdE0K7vEfh1wZ5m48joS5lamVcuXWRn6cZh4v
            peYqTk5FxepZLycNVdmo9Gl+ZfoTCZd528ABdRxG2jjLw428lU0tzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T09:00:52Z"
    mac: ENC[AES256_GCM,data:+7I5AT1UCgTSpYhxjBGn4FT2UhgBRhof6oi3yjpsOEZZW5iNFLCmUhNgD9nHBIlTZ6jbFBPtepWmMJWMKWdMbw36U0cv1iGbG5NhaZcUI4+n9Ilkr4lUfbcWoezNLdbM0Ud1h3NYRbGzMRhQetrE1XNwAkUVUhsPGopHu82LAig=,iv:11+GojRpaunD3wb6tJ3nefXuBNTp4Eg2J2hDCfRep58=,tag:6AyUF6wqguX2nVbJOgZPpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
