xray-client:
    uuid: ENC[AES256_GCM,data:CyMqxbFoiCBnFJ2KB2zozX/KmR+2D3nNUeMu32oeUXNdrpLY,iv:Z8NIHhk+lTU2DqlF8g9BW1ja6EGUuLdA63clZryxYjM=,tag:1yrVCWQwD3WcW2yjiNDU5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmZYc3Yyb3dhRVE0Tkl3
            KzlNSkowb0N4LzF3cWh1ZmVFcGh0WXFzNndNCmJ6N3lBTU9UbmYrOG5yenA2Vm1Y
            SVhOV0dGYUlWM1hEWWZESTdoN0F2Vk0KLS0tIDA3U2FjUHZmTGhxWm9QQ2FnWU1H
            NmsxUlY4dStHRFM2RXd0aXA5UTVnQXcKjG4PrHxOh5y12Yx1BQRRahYDOnIWEtyH
            wTCRDNtDdwma50U7IRAQUZ9i+bjIwQXmxDBHlvguFe7xyi2wBCfXTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m5qqkz7c7tjzyq9cuj25se6ylknqxjph070yj4ap4zx08e0v8vzsgw72qt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL0NOKzd0UXdUaHBiWXFM
            ZEx0K0dqVWZoWEFVUE1DcStkT0s5Wjh3SmpZCkQzNlg3NHNxTXRTVzByNHBybmxD
            WnEzYmtiRTI1bW5TenJsVHczemdWM00KLS0tICsyMFR3T1FnakhXTXpPZWNHUnBk
            RFk4Yng2VEpWN1g5VFZiZ0NxeGpKYWMKCfwmhJuE8RAkdOCzi4IcCrIvbAOvAc26
            HK5KHNQVEeMlkkrNsrgI2Ab4mtxnptPV5eLVNWM81NP7kQA67U4xNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T09:02:57Z"
    mac: ENC[AES256_GCM,data:J9hsyyfOPU5DByjJHqtPr7usYS48siBtC9BK1zsPOofOvMd0UXmBuKUoPCvXfVQVqN9dwC1NMPwUsfzyOvcg5ir1vnAbHSMH6s0yLWyvUOM3QGL8gDayPBf86thyFtTCskciJ2DnFB4pl4n6e6ER+eJ9gVcyrXk5WI8lFqxCR9o=,iv:ELV1nGAlZrR+9tpb/GceevinTegv45D9LhseN84HAqM=,tag:+uxrWMmQv4PFpkJuD70YBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
